//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleAADv2Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleAADv2Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;style type=\&quot;text/css\&quot;&gt;
        ///table.company {
        ///    width: 500px;
        ///    margin: 0 auto;
        ///    border-collapse: separate;
        ///    border-spacing: 0px 15px;
        ///    font-size: 12px;
        ///}
        /// 
        ///table.company th,
        ///table.company td {
        ///    padding: 10px;
        ///}
        /// 
        ///table.company th {
        ///    background: #295890;
        ///    vertical-align: middle;
        ///    text-align: left;
        ///    width: 100px;
        ///    overflow: visible;
        ///    position: relative;
        ///    color: #fff;
        ///    font-weight: normal;
        ///    font-size: 15px;
        ///}
        /// 
        ///table.company th:after {
        ///    left [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Style_Table {
            get {
                return ResourceManager.GetString("Style_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter only numbers.&lt;br&gt;e.g. 60 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AlertDuration {
            get {
                return ResourceManager.GetString("Text_AlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter only E-mail addresses.&lt;br&gt;e.g. abc@company.com, def@government.gov に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AlertEmailAddresses {
            get {
                return ResourceManager.GetString("Text_AlertEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter only numbers.&lt;br&gt;e.g. 3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AlertNumberOfParticipants {
            get {
                return ResourceManager.GetString("Text_AlertNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter only date.&lt;br&gt;e.g. 2015/06/20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_AlertWhen {
            get {
                return ResourceManager.GetString("Text_AlertWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The meeting is arranged. Thank you! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Arranged {
            get {
                return ResourceManager.GetString("Text_Arranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The arrangement is canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Canceled {
            get {
                return ResourceManager.GetString("Text_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The duration of the meeting is  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckDuration1 {
            get {
                return ResourceManager.GetString("Text_CheckDuration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    min. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckDuration2 {
            get {
                return ResourceManager.GetString("Text_CheckDuration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will invite  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckEmailAddresses {
            get {
                return ResourceManager.GetString("Text_CheckEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of participants is  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckNumberOfParticipants1 {
            get {
                return ResourceManager.GetString("Text_CheckNumberOfParticipants1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckNumberOfParticipants2 {
            get {
                return ResourceManager.GetString("Text_CheckNumberOfParticipants2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;table class=\&quot;company\&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;th class=\&quot;arrow_box\&quot;&gt;Subject&lt;/div&gt;&lt;/th&gt;
        ///            &lt;td&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckSubject1 {
            get {
                return ResourceManager.GetString("Text_CheckSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckSubject2 {
            get {
                return ResourceManager.GetString("Text_CheckSubject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You would like to hold the meeting at  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckWhen1 {
            get {
                return ResourceManager.GetString("Text_CheckWhen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_CheckWhen2 {
            get {
                return ResourceManager.GetString("Text_CheckWhen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You would like to hold the meeting with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Confirmation1 {
            get {
                return ResourceManager.GetString("Text_Confirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    at  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Confirmation2 {
            get {
                return ResourceManager.GetString("Text_Confirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    . に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Confirmation3 {
            get {
                return ResourceManager.GetString("Text_Confirmation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is this correct? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Confirmation4 {
            get {
                return ResourceManager.GetString("Text_Confirmation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Hello1 {
            get {
                return ResourceManager.GetString("Text_Hello1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    san!  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Hello2 {
            get {
                return ResourceManager.GetString("Text_Hello2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;b&gt;How long is the duration&lt;/b&gt; of the meeting (min)? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseEnterDuration {
            get {
                return ResourceManager.GetString("Text_PleaseEnterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please list &lt;b&gt;all E-mail addresses&lt;/b&gt; separated by comma. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseEnterEmailAddresses {
            get {
                return ResourceManager.GetString("Text_PleaseEnterEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;b&gt;How many participants&lt;/b&gt; you will invite for the meeting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseEnterNumberOfParticipants {
            get {
                return ResourceManager.GetString("Text_PleaseEnterNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First, please tell me the &lt;b&gt;subject&lt;/b&gt; of the meeting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseEnterSubject {
            get {
                return ResourceManager.GetString("Text_PleaseEnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;b&gt;When&lt;/b&gt; would you like to hold the meeting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseEnterWhen {
            get {
                return ResourceManager.GetString("Text_PleaseEnterWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the date from the following options:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseSelectSchedule {
            get {
                return ResourceManager.GetString("Text_PleaseSelectSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First, please sign in by clicking the link below. &lt;br&gt;Then, please paste back the number you received in your authentication screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_PleaseSignIn {
            get {
                return ResourceManager.GetString("Text_PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome! This is Schedule Bot! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
    }
}
